name: Update Wind Power Forecast

on: 
    schedule:
        - cron: "0 */1 * * *"
jobs:
    refresh-dashboard:
        runs-on: ubuntu-22.04
        container: 
            image: jorgethomasm/wind-power-forecast:prod
        steps:
            - name: checkout_repo
              uses: actions/checkout@v3
              with:
                ref: "main"
            - name: update-power-forecast
              run: bash ./R/update_forecast.sh
              env:
                USER_EMAIL: ${{ secrets.USER_EMAIL }}
                USER_NAME: ${{ secrets.USER_NAME }}
